name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

  workflow_dispatch:

  schedule:
    - cron: '0 14 * * 5' # Runs at 23:00 JST every Friday

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Ruby version: ${{ matrix.ruby }}"
    strategy:
      matrix:
        ruby:
          - '3.3.5' # Initially supported MRI version
          - 'ruby' # Latest MRI

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake

  test-with-ruby-lsp-latest:
    runs-on: ubuntu-latest
    name: Ruby latest with ruby-lsp latest

    steps:
      - uses: actions/checkout@v4
      - name: Remove Gemfile.lock
        run: rm Gemfile.lock
      - name: Replace ruby-lsp version specifier
        run: cat ruby-lsp-rake.gemspec | sed 's/ruby-lsp", "~> 0.23.0"/ruby-lsp", "~> 0.23.11"/' | tee ruby-lsp-rake.gemspec # FIXME: Replace
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
